/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controlador.Conexion;
import Controlador.HuespedData;
import Modelo.Huesped;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Martin
 */
public class FormularioHuespedView extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaHuesped
     */
    public FormularioHuespedView() {
        initComponents();
        this.setSize(600, 500);
        inicializar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTDni = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTDomicilio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTCorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTelefono = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTID = new javax.swing.JTextField();
        jBModificar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBuscar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jRBActivo = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jBNuevo = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        jBNuevaBusqueda = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Huesped");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setText("Huesped");
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 10, 85, 27);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(24, 90, 54, 17);

        jTNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNombreKeyTyped(evt);
            }
        });
        getContentPane().add(jTNombre);
        jTNombre.setBounds(108, 87, 232, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(24, 130, 50, 17);

        jTApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTApellidoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTApellidoKeyTyped(evt);
            }
        });
        getContentPane().add(jTApellido);
        jTApellido.setBounds(108, 127, 232, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Dni:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(24, 164, 25, 17);

        jTDni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTDniKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTDniKeyTyped(evt);
            }
        });
        getContentPane().add(jTDni);
        jTDni.setBounds(108, 161, 233, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Domicilio:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(24, 198, 58, 17);

        jTDomicilio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTDomicilio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTDomicilioKeyPressed(evt);
            }
        });
        getContentPane().add(jTDomicilio);
        jTDomicilio.setBounds(108, 195, 232, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Correo:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(24, 232, 47, 17);

        jTCorreo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTCorreoKeyPressed(evt);
            }
        });
        getContentPane().add(jTCorreo);
        jTCorreo.setBounds(108, 229, 232, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Telefono:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(24, 266, 57, 17);

        jTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(jTelefono);
        jTelefono.setBounds(108, 263, 232, 23);

        jBGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jBGuardar);
        jBGuardar.setBounds(24, 336, 81, 25);

        jBSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBSalir);
        jBSalir.setBounds(440, 336, 57, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Id Huesped:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(24, 53, 74, 17);

        jTID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTIDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTIDKeyTyped(evt);
            }
        });
        getContentPane().add(jTID);
        jTID.setBounds(108, 51, 232, 23);

        jBModificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jBModificar);
        jBModificar.setBounds(129, 336, 85, 25);

        jBEliminar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jBEliminar);
        jBEliminar.setBounds(232, 336, 79, 25);

        jBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBuscar.setText("Confirmar Busqueda");
        jBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jBuscar);
        jBuscar.setBounds(393, 141, 157, 25);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Activo:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(24, 297, 43, 17);
        getContentPane().add(jRBActivo);
        jRBActivo.setBounds(108, 297, 21, 21);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(24, 40, 526, 10);

        jBNuevo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBNuevo.setText("Nuevo Huesped");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(jBNuevo);
        jBNuevo.setBounds(393, 50, 157, 25);

        jBLimpiar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBLimpiar.setText("Limpiar");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jBLimpiar);
        jBLimpiar.setBounds(329, 336, 75, 25);

        jBNuevaBusqueda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBNuevaBusqueda.setText("Nueva busqueda");
        jBNuevaBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevaBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(jBNuevaBusqueda);
        jBNuevaBusqueda.setBounds(393, 98, 157, 25);
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
       Conexion con= new Conexion();
       HuespedData huesp=new HuespedData(con);
       
       if (vacio())
       { JOptionPane.showMessageDialog(null, "Hay campos vacios, verifique antes de guardar");}
       else
       { String nombre= jTNombre.getText();
         String apellido=jTApellido.getText();
         int dni=Integer.parseInt(jTDni.getText());
         String domicilio=jTDomicilio.getText();
         String correo=jTCorreo.getText();
         String telefono= jTelefono.getText();
         boolean activo=jRBActivo.isSelected();
       
         Huesped huesped= new Huesped(nombre, apellido, dni, domicilio, correo, telefono, activo);
       
         huesp.guardarHuesped(huesped);
       } 
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jTNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNombreKeyPressed
     if(evt.getKeyCode()== KeyEvent.VK_ENTER)
           jTApellido.requestFocus();
    }//GEN-LAST:event_jTNombreKeyPressed

    private void jTApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTApellidoKeyPressed
       if(evt.getKeyCode()== KeyEvent.VK_ENTER)
           jTDni.requestFocus();
    }//GEN-LAST:event_jTApellidoKeyPressed

    private void jTDniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDniKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
           jTDomicilio.requestFocus();
    }//GEN-LAST:event_jTDniKeyPressed

    private void jTDomicilioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDomicilioKeyPressed
       if(evt.getKeyCode()== KeyEvent.VK_ENTER)
           jTCorreo.requestFocus();
    }//GEN-LAST:event_jTDomicilioKeyPressed

    private void jTCorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCorreoKeyPressed
      if(evt.getKeyCode()== KeyEvent.VK_ENTER)
          jTelefono.requestFocus();
    }//GEN-LAST:event_jTCorreoKeyPressed

    private void jTIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTIDKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
           jTNombre.requestFocus();
    }//GEN-LAST:event_jTIDKeyPressed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        jTID.setEnabled(false);
        jBNuevo.setEnabled(false);
        jBuscar.setEnabled(false);
        jBNuevaBusqueda.setEnabled(false);
        jBGuardar.setEnabled(true);
        jBModificar.setEnabled(false);
        jBEliminar.setEnabled(false);
        jRBActivo.setEnabled(true);
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jTIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTIDKeyTyped
      noNumero(evt);
    }//GEN-LAST:event_jTIDKeyTyped

    private void jTNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNombreKeyTyped
       noCaracter(evt);
    }//GEN-LAST:event_jTNombreKeyTyped

    private void jTApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTApellidoKeyTyped
       noCaracter(evt);
    }//GEN-LAST:event_jTApellidoKeyTyped

    private void jTDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDniKeyTyped
       noNumero(evt);
    }//GEN-LAST:event_jTDniKeyTyped

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
       limpiar();
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTelefonoKeyTyped
       noNumero(evt);
    }//GEN-LAST:event_jTelefonoKeyTyped

    private void jBNuevaBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevaBusquedaActionPerformed
        JOptionPane.showMessageDialog(null, "La busqueda puede realizarce por ID del huesped o por su DNI");
        desactivarCText();
        jBNuevo.setEnabled(false);
        jBuscar.setEnabled(true);
        jBModificar.setEnabled(true);
        jBEliminar.setEnabled(true);
        jBLimpiar.setEnabled(true);
        jTID.setEnabled(true);
        jTDni.setEnabled(true);
    }//GEN-LAST:event_jBNuevaBusquedaActionPerformed

    private void jBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarActionPerformed
       Conexion con = new Conexion();
       HuespedData hd = new HuespedData(con);
       Huesped huesped= new Huesped();
       
       activarCText();
       
       if (!jTID.getText().equals(""))
       { huesped=hd.buscarHuesped(Integer.parseInt(jTID.getText()));
         
         jTNombre.setText(huesped.getNombre());
         jTApellido.setText(huesped.getApellido());
         jTDni.setText(String.valueOf(huesped.getDni()));
         jTDomicilio.setText(huesped.getDomicilio());
         jTCorreo.setText(huesped.getCorreo());
         jTelefono.setText(String.valueOf(huesped.getTelefono()));
         jRBActivo.setSelected(huesped.isActivo());
       }
       else
           if(!jTDni.getText().equals(""))
           {  huesped=hd.buscarHuespedPorDni(Integer.parseInt(jTDni.getText()));              
              
              jTID.setText(String.valueOf(huesped.getIdhuesped()));
              jTNombre.setText(huesped.getNombre());
              jTApellido.setText(huesped.getApellido());
              jTDomicilio.setText(huesped.getDomicilio());
              jTCorreo.setText(huesped.getCorreo());
              jTelefono.setText(String.valueOf(huesped.getTelefono()));
              jRBActivo.setSelected(huesped.isActivo());
           }
          else
               JOptionPane.showMessageDialog(null, "Los campos ID o DNI no pueden estar vacios");
    }//GEN-LAST:event_jBuscarActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
       Conexion con = new Conexion();
       HuespedData hd = new HuespedData(con);
             
         if (vacio())
       { JOptionPane.showMessageDialog(null, "Hay campos vacios, verifique antes de guardar");}
       else
       { int idHuesped=Integer.parseInt(jTID.getText());
         String nombre= jTNombre.getText();
         String apellido=jTApellido.getText();
         int dni=Integer.parseInt(jTDni.getText());
         String domicilio=jTDomicilio.getText();
         String correo=jTCorreo.getText();
         String telefono= jTelefono.getText();
         boolean activo=jRBActivo.isSelected();
       
         Huesped huesped= new Huesped(nombre, apellido, dni, domicilio, correo, telefono, activo);
       
         hd.modificarHuesped(idHuesped,huesped);
       }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
       Conexion con = new Conexion();
       HuespedData hd = new HuespedData(con);
       
       Integer id= Integer.parseInt(jTID.getText());
       
       if (jRBActivo.isSelected())
           hd.eliminarHuesped(id);
         else
           JOptionPane.showMessageDialog(null," Verifica la casilla que indica si esta activo o no el huseped");
    }//GEN-LAST:event_jBEliminarActionPerformed

private void limpiar()  
{ jTID.setText("");
  jTNombre.setText("");
  jTApellido.setText("");
  jTDni.setText("");
  jTDomicilio.setText("");
  jTCorreo.setText("");
  jTelefono.setText("");
  jRBActivo.setSelected(false);
  inicializar();
}

private void desactivarCText()
{       jTID.setEnabled(false);
        jTNombre.setEnabled(false);
        jTApellido.setEnabled(false);
        jTDni.setEnabled(false);
        jTDomicilio.setEnabled(false);
        jTCorreo.setEnabled(false);
        jTelefono.setEnabled(false);
        jRBActivo.setEnabled(false);
}

private void activarCText()
{       jTID.setEnabled(true);
        jTNombre.setEnabled(true);
        jTApellido.setEnabled(true);
        jTDni.setEnabled(true);
        jTDomicilio.setEnabled(true);
        jTCorreo.setEnabled(true);
        jTelefono.setEnabled(true);
        jRBActivo.setEnabled(true);
}

private void inicializar()
{       jBNuevo.setEnabled(true);
        jBNuevaBusqueda.setEnabled(true);
        jBuscar.setEnabled(false);
        jBGuardar.setEnabled(false);
        jBModificar.setEnabled(false);
        jBEliminar.setEnabled(false);
        jBLimpiar.setEnabled(true);
}
private boolean vacio()
{ boolean vacio=false;

    if (jTNombre.getText().equals("") || jTApellido.getText().equals("") || jTDni.getText(
       ).equals("")|| jTDomicilio.getText().equals("")|| jTCorreo.getText().equals("")||
       jTelefono.equals(""))
    {  vacio=true;
       
    }
  return(vacio);
}

public void noNumero(java.awt.event.KeyEvent evt)
{  if(!Character.isDigit(evt.getKeyChar()))
{  //getToolkit().beep();
  evt.consume();
}
}

public void noCaracter(java.awt.event.KeyEvent evt)
{  if(!(Character.isLetter(evt.getKeyChar())||evt.getKeyChar()== KeyEvent.VK_SPACE))
evt.consume();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBNuevaBusqueda;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRBActivo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JTextField jTCorreo;
    private javax.swing.JTextField jTDni;
    private javax.swing.JTextField jTDomicilio;
    private javax.swing.JTextField jTID;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTelefono;
    // End of variables declaration//GEN-END:variables
}
