/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controlador.CategoriaData;
import Controlador.Conexion;
import Controlador.HabitacionData;
import Modelo.Categoria;
import Modelo.Habitacion;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Anto
 */
public class FormularioHabitacionView extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioHabitacionView
     */
    
    FondoPanel fondo = new FondoPanel();
    
    public FormularioHabitacionView() {
        
        initComponents();
        buttonModificar.setEnabled(false);
        buttonEstado.setEnabled(false);
        JOptionPane.showMessageDialog(this, "Recuerde: para añadir una habitacion la categoria ya debe de estar creada ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jtIdHabitacion = new javax.swing.JTextField();
        buttonBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtNmroHabitacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtPiso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtIdCategoria = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        radioEstado = new javax.swing.JRadioButton();
        buttonGuardar = new javax.swing.JButton();
        buttonModificar = new javax.swing.JButton();
        buttonEstado = new javax.swing.JButton();
        buttonLimpiar = new javax.swing.JButton();
        buttonSalir = new javax.swing.JButton();

        setResizable(true);
        setTitle("Habitacion");
        setMinimumSize(new java.awt.Dimension(500, 450));

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 16)); // NOI18N
        jLabel1.setText("Habitacion");

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel2.setText("Id habitación:");

        buttonBuscar.setText("Buscar");
        buttonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel3.setText("Número habitación:");

        jtNmroHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNmroHabitacionActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel4.setText("Piso:");

        jtPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPisoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel5.setText("Id Categoria:");

        jtIdCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtIdCategoriaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel6.setText("Refaccion:");

        buttonGuardar.setText("Guardar");
        buttonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarActionPerformed(evt);
            }
        });

        buttonModificar.setText("Modificar");
        buttonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModificarActionPerformed(evt);
            }
        });

        buttonEstado.setText("Cambiar estado");
        buttonEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEstadoActionPerformed(evt);
            }
        });

        buttonLimpiar.setText("Limpiar");
        buttonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimpiarActionPerformed(evt);
            }
        });

        buttonSalir.setText("Salir");
        buttonSalir.setMinimumSize(new java.awt.Dimension(500, 400));
        buttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2))
                            .addGap(37, 37, 37)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtNmroHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jtIdHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(100, 100, 100)
                                    .addComponent(buttonBuscar)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(buttonGuardar)
                            .addGap(18, 18, 18)
                            .addComponent(buttonModificar)
                            .addGap(33, 33, 33)
                            .addComponent(buttonEstado)
                            .addGap(18, 18, 18)
                            .addComponent(buttonLimpiar)
                            .addGap(18, 18, 18)
                            .addComponent(buttonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtIdHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(buttonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtNmroHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(radioEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonGuardar)
                    .addComponent(buttonModificar)
                    .addComponent(buttonEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonLimpiar)
                    .addComponent(buttonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_buttonSalirActionPerformed

    private void buttonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarActionPerformed
        // TODO add your handling code here:
        Conexion con = new Conexion();
        try {
            Integer id = Integer.parseInt(jtIdHabitacion.getText());
            Habitacion habitacion = new HabitacionData(con).buscarHabitacion(id);
            if (habitacion != null) {
                //Cambiar int a string
                String idHabi = String.valueOf(habitacion.getIdHabitacion());
                jtIdHabitacion.setText(idHabi);
                radioEstado.setSelected(habitacion.isRefaccion());
                String nmroHabitacion = String.valueOf(habitacion.getNroHabitacion());
                jtNmroHabitacion.setText(nmroHabitacion);
                String piso = String.valueOf(habitacion.getPiso());
                jtPiso.setText(piso);
                String idCat = String.valueOf(habitacion.obtengoIdCategoria());
                jtIdCategoria.setText(idCat);

                buttonModificar.setEnabled(true);
                buttonEstado.setEnabled(true);

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El dato no es numerico, vuelve a ingresarlo ");
            jtIdHabitacion.requestFocus();
            limpiar();
        }
    }//GEN-LAST:event_buttonBuscarActionPerformed

    private void buttonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_buttonLimpiarActionPerformed

    private void jtNmroHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNmroHabitacionActionPerformed
        // TODO add your handling code here:ç
        try {
            int nmroHabitacion = Integer.parseInt(jtNmroHabitacion.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El dato no es numerico, vuelve a ingresarlo ");
            jtNmroHabitacion.requestFocus();
            limpiar();
        }
    }//GEN-LAST:event_jtNmroHabitacionActionPerformed

    private void jtPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPisoActionPerformed
        // TODO add your handling code here:
        try {
            int piso = Integer.parseInt(jtPiso.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El dato no es numerico, vuelve a ingresarlo ");
            jtPiso.requestFocus();
            limpiar();
        }
    }//GEN-LAST:event_jtPisoActionPerformed

    private void jtIdCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtIdCategoriaActionPerformed
        // TODO add your handling code here:

        try {

            int piso = Integer.parseInt(jtPiso.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El dato no es numerico, vuelve a ingresarlo ");
            jtPiso.requestFocus();
            limpiar();
        }
    }//GEN-LAST:event_jtIdCategoriaActionPerformed

    private void buttonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardarActionPerformed
        // TODO add your handling code here:
        if (vacio()) {
            Conexion con = new Conexion();
            HabitacionData ad = new HabitacionData(con);

            Categoria cat = new CategoriaData(con).buscarCategoria(Integer.parseInt(jtIdCategoria.getText()));
            cat.getIdCategoria();

            Integer nmro = Integer.parseInt(jtNmroHabitacion.getText());
            Integer piso = Integer.parseInt(jtPiso.getText());

            Boolean estado;
            if (radioEstado.isSelected()) {
                estado = true;
            } else {
                estado = false;
            }
            Habitacion habitacion = new Habitacion(cat, nmro, piso, estado);

            ad.agregarHabitacion(habitacion);
        } else {
            JOptionPane.showMessageDialog(this, "Hay campos para revisar, no deben quedar vacios");
        }

    }//GEN-LAST:event_buttonGuardarActionPerformed

    private void buttonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarActionPerformed
        // TODO add your handling code here:
        if (vacio()) {
            Conexion con = new Conexion();
            HabitacionData ad = new HabitacionData(con);

            //Categoria cat = jtIdCategoria.getText();
            Categoria cat = new CategoriaData(con).buscarCategoria(Integer.parseInt(jtIdCategoria.getText()));
            cat.getIdCategoria();

            Integer nmro = Integer.parseInt(jtNmroHabitacion.getText());
            Integer piso = Integer.parseInt(jtPiso.getText());
            Integer idHabitacion = Integer.parseInt(jtIdHabitacion.getText());

            Boolean estado = false;

            Habitacion habitacion = new Habitacion(cat, nmro, piso, estado);

            ad.modificarHabitacion(idHabitacion, habitacion);
        } else {
            JOptionPane.showMessageDialog(this, "Hay campos para revisar, no deben quedar vacios");
        }
    }//GEN-LAST:event_buttonModificarActionPerformed

    private void buttonEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEstadoActionPerformed
        // TODO add your handling code here:
        Conexion con = new Conexion();
        HabitacionData hd = new HabitacionData(con);

        Integer id = Integer.parseInt(jtIdHabitacion.getText());

        if (radioEstado.isSelected()) {
            hd.habilitarHabitacion(id);
        } else {
            hd.deshabilitarHabitacion(id);
        }
    }//GEN-LAST:event_buttonEstadoActionPerformed

    public void limpiar() {
        jtIdHabitacion.setText("");
        jtNmroHabitacion.setText("");
        jtPiso.setText("");
        jtIdCategoria.setText("");
        radioEstado.setSelected(false);
    }

    private boolean vacio() {
        String str = "";
        if (!str.equals(jtNmroHabitacion.getText()) && !str.equals(jtPiso.getText()) && !str.equals(jtIdCategoria.getText())) {
            return true;
        } else {
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton buttonEstado;
    private javax.swing.JButton buttonGuardar;
    private javax.swing.JButton buttonLimpiar;
    private javax.swing.JButton buttonModificar;
    private javax.swing.JButton buttonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jtIdCategoria;
    private javax.swing.JTextField jtIdHabitacion;
    private javax.swing.JTextField jtNmroHabitacion;
    private javax.swing.JTextField jtPiso;
    private javax.swing.JRadioButton radioEstado;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel{
        private Image imagen;
        @Override
        public void paint (Graphics g){
            imagen = new ImageIcon(getClass().getResource("/imagen/habitacion2.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
          
    }
}
