package Vistas;

import Controlador.Conexion;
import Controlador.HabitacionData;
import Controlador.HuespedData;
import Controlador.ReservaData;
import Modelo.Categoria;
import Modelo.Habitacion;
import Modelo.Huesped;
import Modelo.Reserva;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anto
 */
public class FormularioReservaView extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioReservaView
     */
    FondoPanel fondo = new FondoPanel();

    private HuespedData HuesData;
    private ReservaData resData;
    private HabitacionData habData;

    private ArrayList<Huesped> listaH;
    private ArrayList<Habitacion> listaHab;
    private Conexion conexion;
    private DefaultTableModel modelo;

    public FormularioReservaView() {
        initComponents();
        conexion = new Conexion();
        HuesData = new HuespedData(conexion);
        habData = new HabitacionData(conexion);
        listaH = (ArrayList<Huesped>) HuesData.listarHuespedes();
        listaHab = (ArrayList<Habitacion>) habData.listarHabitaciones();
        modelo = (DefaultTableModel) jTable1.getModel();
        cargaHuesped();
        cargaHabitacion();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel()
        ;
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        boxHuesped = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fechaInicio = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        fechaFin = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jtCantPersonas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        radioEstado = new javax.swing.JRadioButton();
        jtPrecio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        radioHabLibres = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonReservar = new javax.swing.JButton();
        buttonAnular = new javax.swing.JButton();
        buttonSalir = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTidReserva = new javax.swing.JTextField();
        jRHabOcupadas = new javax.swing.JRadioButton();
        jBBuscarId = new javax.swing.JButton();
        comboHabitacion = new javax.swing.JComboBox<>();

        setTitle("Reserva");
        setMinimumSize(new java.awt.Dimension(500, 500));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Reservas:");

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccione un huesped:");

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha Inicio:");

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha Fin:");

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cantidad de personas:");

        jtCantPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCantPersonasActionPerformed(evt);
            }
        });
        jtCantPersonas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtCantPersonasKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Calligraphy", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Estado:");

        jtPrecio.setText("$");
        jtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPrecioActionPerformed(evt);
            }
        });
        jtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtPrecioKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Calligraphy", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Precio:");

        jLabel9.setFont(new java.awt.Font("Lucida Calligraphy", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Listado de Habitaciones:");

        radioHabLibres.setText("Habitaciones libres");
        radioHabLibres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioHabLibresActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Habitacion", "Numero Habitacion", "Id Categoria", "Refaccion", "Piso"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        buttonReservar.setText("Reservar");
        buttonReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReservarActionPerformed(evt);
            }
        });

        buttonAnular.setText("Anular");
        buttonAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnularActionPerformed(evt);
            }
        });

        buttonSalir.setText("Salir");
        buttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalirActionPerformed(evt);
            }
        });

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Numero de Habitacion:");

        jLabel10.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("id Reserva:");

        jTidReserva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTidReservaKeyTyped(evt);
            }
        });

        jRHabOcupadas.setText("Habitaciones Ocupadas");
        jRHabOcupadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRHabOcupadasActionPerformed(evt);
            }
        });

        jBBuscarId.setText("Buscar");
        jBBuscarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jtCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))))
                                        .addGap(32, 32, 32))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radioEstado)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(204, 204, 204)
                                                .addComponent(jBBuscarId)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)))
                                .addComponent(fechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRHabOcupadas)
                                .addGap(108, 108, 108)
                                .addComponent(radioHabLibres))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTidReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(101, 101, 101)))
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(buttonReservar)
                        .addGap(29, 29, 29)
                        .addComponent(buttonAnular)
                        .addGap(64, 64, 64)
                        .addComponent(jBModificar)
                        .addGap(28, 28, 28)
                        .addComponent(buttonSalir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTidReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscarId))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jtCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(radioEstado))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(fechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fechaFin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioHabLibres)
                    .addComponent(jRHabOcupadas))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonReservar)
                    .addComponent(buttonAnular)
                    .addComponent(buttonSalir)
                    .addComponent(jBModificar))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_buttonSalirActionPerformed

    private void buttonReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReservarActionPerformed
        // TODO add your handling code here:
        if (vacio()) {
            resData = new ReservaData(conexion);
            int filaSeleccionada = jTable1.getSelectedRow();
            if (filaSeleccionada != -1) {
                Huesped hues = (Huesped) boxHuesped.getSelectedItem();
                habData = new HabitacionData(conexion);
                Habitacion hab = habData.buscarHabitacion((int) jTable1.getValueAt((int) jTable1.getSelectedRow(), 0));

                //JCalendar --> Date--> LocalDate
                Date fecha1 = fechaInicio.getDate();
                LocalDate fechaI = fecha1.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                Date fecha2 = fechaFin.getDate();
                LocalDate fechaF = fecha2.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                //String--> Double
                String pre = jtPrecio.getText();
                Double precio = Double.parseDouble(pre);
                //String-->Int
                String cant = jtCantPersonas.getText();
                int cantPersonas = Integer.parseInt(cant);
                boolean estado;
                if (radioEstado.isSelected()) {
                    estado = true;
                } else {
                    estado = false;
                }

                Reserva re = new Reserva(hab, hues, fechaI, fechaF, precio, cantPersonas, estado);

                resData.reservar(re);
                borrarFilaTabla();
            } else {
                JOptionPane.showMessageDialog(this, "Hay campos para revisar, no deben quedar vacios");
            }
        }

    }//GEN-LAST:event_buttonReservarActionPerformed

    private void buttonAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnularActionPerformed
        // TODO add your handling code here:
        resData = new ReservaData(conexion);
        habData = new HabitacionData(conexion);
        int filaSeleccionada = jTable1.getSelectedRow();

        if (filaSeleccionada != -1) {
            //modelo.setRowCount(0);
            Huesped hues = (Huesped) boxHuesped.getSelectedItem();
            int idHuesped = hues.getIdhuesped();
            Habitacion hab = habData.buscarHabitacion((int) jTable1.getValueAt((int) jTable1.getSelectedRow(), 0));
            int idHabitacion = hab.getIdHabitacion();
            resData.anularReserva(idHuesped, idHabitacion);
            // borrarFilaTabla();

        }

    }//GEN-LAST:event_buttonAnularActionPerformed

    private void radioHabLibresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioHabLibresActionPerformed
        // TODO add your handling code here:
        if (vacio()) {
            jRHabOcupadas.setSelected(false);
            borrarFilaTabla();
            cargaHabLibres();
            buttonAnular.setEnabled(false);
            buttonReservar.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor complete los campos del formulario");
        }
    }//GEN-LAST:event_radioHabLibresActionPerformed

    private void jtCantPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCantPersonasActionPerformed
        // TODO add your handling code here:
        try {
            int cant = Integer.parseInt(jtCantPersonas.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El dato no es numerico, vuelve a ingresarlo ");
            jtCantPersonas.requestFocus();
            limpiar();
        }
    }//GEN-LAST:event_jtCantPersonasActionPerformed

    private void jtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPrecioActionPerformed
        try {
            int precio = Integer.parseInt(jtPrecio.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El dato no es numerico, vuelve a ingresarlo ");
            jtPrecio.requestFocus();
            limpiar();
        }
    }//GEN-LAST:event_jtPrecioActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        Conexion con = new Conexion();
        ReservaData reserd = new ReservaData(con);
        
        if (vacio()){
            JOptionPane.showMessageDialog(null, "Hay campos vacios, verifique antes de modificar");
        }else{
            
            Huesped hues = new HuespedData(con).buscarHuesped((boxHuesped.getSelectedIndex()));
            hues.getIdhuesped();
                    
            Habitacion habi = new HabitacionData(con).buscarHabitacion((comboHabitacion.getSelectedIndex()));
            habi.getIdHabitacion();
            
            int idReserva = Integer.parseInt(jTidReserva.getText());
            
            Date fecha1 = fechaInicio.getDate();
            LocalDate inicio = fecha1.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            Date fecha2 = fechaFin.getDate();
            LocalDate fin = fecha2.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            double precio = Double.parseDouble(jtPrecio.getText());
            int cantiPersonas = (Integer.parseInt(jtCantPersonas.getText()));
            boolean activo = radioEstado.isSelected();
            
            Reserva reserva = new Reserva(habi,hues,inicio,fin,precio,cantiPersonas,activo);
            
            reserd.modificarReserva(idReserva, reserva);
        }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPrecioKeyTyped
        noNumero(evt);
    }//GEN-LAST:event_jtPrecioKeyTyped

    private void jtCantPersonasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCantPersonasKeyTyped
        noNumero(evt);
    }//GEN-LAST:event_jtCantPersonasKeyTyped

    private void jTidReservaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTidReservaKeyTyped
        noNumero(evt);
    }//GEN-LAST:event_jTidReservaKeyTyped

    private void jRHabOcupadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRHabOcupadasActionPerformed
        if (vacio()) {
            radioHabLibres.setSelected(false);
            borrarFilaTabla();
            cargaHabReservadas();
            buttonAnular.setEnabled(true);
            buttonReservar.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor complete los campos del formulario");
        }
    }//GEN-LAST:event_jRHabOcupadasActionPerformed

    private void jBBuscarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarIdActionPerformed
        Conexion con = new Conexion();
        ReservaData rsdata = new ReservaData(con);
        Reserva reser = new Reserva();
        Habitacion hab = new Habitacion();
        Huesped hues = new Huesped();
        
        
       
        
        if(!jTidReserva.getText().equals("")){
            reser = rsdata.buscarReserva(Integer.parseInt(jTidReserva.getText()));
            
            comboHabitacion.setSelectedItem(reser.getHabitacion());
            boxHuesped.setSelectedItem(reser.getHuesped());
            
            LocalDate lc = reser.getFechaInicio();
            Date date = Date.from(lc.atStartOfDay(ZoneId.systemDefault()).toInstant());
            fechaInicio.setDate(date);
            
            LocalDate loc = reser.getFechaFin();
            Date date2 = Date.from(loc.atStartOfDay(ZoneId.systemDefault()).toInstant());
            fechaFin.setDate(date2);
            
            jtPrecio.setText(String.valueOf(reser.getPrecioTotal()));
            jtCantPersonas.setText(String.valueOf(reser.getCantPersonas()));
            radioEstado.setEnabled(reser.isActivo());
        }
        else{
            JOptionPane.showMessageDialog(null, "El id no puede quedar vacio");
        }
       
    }//GEN-LAST:event_jBBuscarIdActionPerformed

    public void limpiar() {
        jtCantPersonas.setText("");
        jtPrecio.setText("");
        radioEstado.setSelected(false);
    }

    private void cargaHuesped() { // Carga al combo box
        for (Huesped item : listaH) {
            boxHuesped.addItem(item);
        }
    }
    
    private void cargaHabitacion(){ // Carga al combo box
        for(Habitacion item: listaHab){
            comboHabitacion.addItem(item);
        }
    }

    private void borrarFilaTabla() {
        int indice = modelo.getRowCount() - 1;

        for (int i = indice; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

    
     private void cargaHabReservadas(){
        //borrarFilasTabla();
        
        Date fecha1 = fechaInicio.getDate();
        LocalDate fechaI = fecha1.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        
        Date fecha2 = fechaFin.getDate();
        LocalDate fechaF = fecha2.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
         resData= new ReservaData(conexion);
       
         listaHab = (ArrayList) resData.obtenerHabitacionesOcupadas(fechaI,fechaF);
        
        
        modelo.setRowCount(0);
         
         listaHab.forEach((h) -> {
             modelo.addRow(new Object[] { h.getIdHabitacion(), h.getNroHabitacion(), h.obtengoIdCategoria(), h.isRefaccion(), h.getPiso()});
        });
         
    }
    

    private void cargaHabLibres() {
        //borrarFilasTabla();
        Date fecha1 = fechaInicio.getDate();
        LocalDate fechaI = fecha1.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        Date fecha2 = fechaFin.getDate();
        LocalDate fechaF = fecha2.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        resData = new ReservaData(conexion);
        List<Habitacion> lista = resData.obtenerHabitacionesLibres(fechaI, fechaF);
        modelo.setRowCount(0);
        for (Habitacion h : lista) {
            modelo.addRow(new Object[]{h.getIdHabitacion(), h.getNroHabitacion(), h.obtengoIdCategoria(), h.isRefaccion(), h.getPiso()});
        }
    }

    private boolean vacio() {
        String str = "";
        if (!str.equals(jtPrecio.getText()) && !str.equals(jtCantPersonas.getText()) && !str.equals(fechaInicio.getDate()) && !str.equals(fechaFin.getDate()) && !str.equals(jtPrecio.getText())) {
            return true;
        } else {
            return false;
        }
    }
    
    public void noNumero(java.awt.event.KeyEvent evt) {
        if (!Character.isDigit(evt.getKeyChar())) {  //getToolkit().beep();
            
            evt.consume();
        }
    }

    public void noCaracter(java.awt.event.KeyEvent evt) {
        if (!(Character.isLetter(evt.getKeyChar()) || evt.getKeyChar() == KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Huesped> boxHuesped;
    private javax.swing.JButton buttonAnular;
    private javax.swing.JButton buttonReservar;
    private javax.swing.JButton buttonSalir;
    private javax.swing.JComboBox<Habitacion> comboHabitacion;
    private com.toedter.calendar.JDateChooser fechaFin;
    private com.toedter.calendar.JDateChooser fechaInicio;
    private javax.swing.JButton jBBuscarId;
    private javax.swing.JButton jBModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRHabOcupadas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTidReserva;
    private javax.swing.JTextField jtCantPersonas;
    private javax.swing.JTextField jtPrecio;
    private javax.swing.JRadioButton radioEstado;
    private javax.swing.JRadioButton radioHabLibres;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagen/reserva2.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }

    }

}
