/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controlador.Conexion;
import Controlador.HuespedData;
import Modelo.Huesped;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Martin
 */
public class FormularioHuespedView extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaHuesped
     */
    
    FondoPanel fondo = new FondoPanel();
    
    public FormularioHuespedView() {
        this.setContentPane(fondo);
        initComponents();
        this.setSize(600, 500);
        inicializar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTDni = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTDomicilio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTCorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTelefono = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTID = new javax.swing.JTextField();
        jBModificar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBuscar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jRBActivo = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jBNuevo = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        jBNuevaBusqueda = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Huesped");

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Huesped");
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 400));

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");

        jTNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNombreKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido:");

        jTApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTApellidoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTApellidoKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dni:");

        jTDni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTDniKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTDniKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Domicilio:");

        jTDomicilio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTDomicilio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTDomicilioKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Correo:");

        jTCorreo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTCorreoKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Telefono:");

        jTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTelefonoKeyTyped(evt);
            }
        });

        jBGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Id Huesped:");

        jTID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTIDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTIDKeyTyped(evt);
            }
        });

        jBModificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jBEliminar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBuscar.setText("Confirmar Busqueda");
        jBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Activo:");

        jBNuevo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBNuevo.setText("Nuevo Huesped");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jBLimpiar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBLimpiar.setText("Limpiar");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });

        jBNuevaBusqueda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBNuevaBusqueda.setText("Nueva busqueda");
        jBNuevaBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevaBusquedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(63, 63, 63))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(84, 84, 84)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                        .addComponent(jTCorreo)
                                        .addComponent(jTelefono))
                                    .addComponent(jRBActivo)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTDni, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTApellido)
                                            .addComponent(jTNombre)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jBGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(jBModificar)
                                .addGap(18, 18, 18)
                                .addComponent(jBEliminar)))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBuscar)
                            .addComponent(jBNuevaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 390, Short.MAX_VALUE)
                .addComponent(jBLimpiar)
                .addGap(18, 18, 18)
                .addComponent(jBSalir)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jBNuevo))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jBNuevaBusqueda)
                        .addGap(18, 18, 18)
                        .addComponent(jBuscar)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jRBActivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGuardar)
                    .addComponent(jBModificar)
                    .addComponent(jBEliminar)
                    .addComponent(jBLimpiar)
                    .addComponent(jBSalir))
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
       Conexion con= new Conexion();
       HuespedData huesp=new HuespedData(con);
       
       if (vacio())
       { JOptionPane.showMessageDialog(null, "Hay campos vacios, verifique antes de guardar");}
       else
       { String nombre= jTNombre.getText();
         String apellido=jTApellido.getText();
         int dni=Integer.parseInt(jTDni.getText());
         String domicilio=jTDomicilio.getText();
         String correo=jTCorreo.getText();
         String telefono= jTelefono.getText();
         boolean activo=jRBActivo.isSelected();
       
         Huesped huesped= new Huesped(nombre, apellido, dni, domicilio, correo, telefono, activo);
       
         huesp.guardarHuesped(huesped);
       } 
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jTNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNombreKeyPressed
     if(evt.getKeyCode()== KeyEvent.VK_ENTER)
           jTApellido.requestFocus();
    }//GEN-LAST:event_jTNombreKeyPressed

    private void jTApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTApellidoKeyPressed
       if(evt.getKeyCode()== KeyEvent.VK_ENTER)
           jTDni.requestFocus();
    }//GEN-LAST:event_jTApellidoKeyPressed

    private void jTDniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDniKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
           jTDomicilio.requestFocus();
    }//GEN-LAST:event_jTDniKeyPressed

    private void jTDomicilioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDomicilioKeyPressed
       if(evt.getKeyCode()== KeyEvent.VK_ENTER)
           jTCorreo.requestFocus();
    }//GEN-LAST:event_jTDomicilioKeyPressed

    private void jTCorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCorreoKeyPressed
      if(evt.getKeyCode()== KeyEvent.VK_ENTER)
          jTelefono.requestFocus();
    }//GEN-LAST:event_jTCorreoKeyPressed

    private void jTIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTIDKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
           jTNombre.requestFocus();
    }//GEN-LAST:event_jTIDKeyPressed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        jTID.setEnabled(false);
        jBNuevo.setEnabled(false);
        jBuscar.setEnabled(false);
        jBNuevaBusqueda.setEnabled(false);
        jBGuardar.setEnabled(true);
        jBModificar.setEnabled(false);
        jBEliminar.setEnabled(false);
        jRBActivo.setEnabled(true);
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jTIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTIDKeyTyped
      noNumero(evt);
    }//GEN-LAST:event_jTIDKeyTyped

    private void jTNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNombreKeyTyped
       noCaracter(evt);
    }//GEN-LAST:event_jTNombreKeyTyped

    private void jTApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTApellidoKeyTyped
       noCaracter(evt);
    }//GEN-LAST:event_jTApellidoKeyTyped

    private void jTDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDniKeyTyped
       noNumero(evt);
    }//GEN-LAST:event_jTDniKeyTyped

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
       limpiar();
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTelefonoKeyTyped
       noNumero(evt);
    }//GEN-LAST:event_jTelefonoKeyTyped

    private void jBNuevaBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevaBusquedaActionPerformed
        JOptionPane.showMessageDialog(null, "La busqueda puede realizarce por ID del huesped o por su DNI");
        desactivarCText();
        jBNuevo.setEnabled(false);
        jBuscar.setEnabled(true);
        jBModificar.setEnabled(true);
        jBEliminar.setEnabled(true);
        jBLimpiar.setEnabled(true);
        jTID.setEnabled(true);
        jTDni.setEnabled(true);
    }//GEN-LAST:event_jBNuevaBusquedaActionPerformed

    private void jBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarActionPerformed
       Conexion con = new Conexion();
       HuespedData hd = new HuespedData(con);
       Huesped huesped= new Huesped();
       
       activarCText();
       
       if (!jTID.getText().equals(""))
       { huesped=hd.buscarHuesped(Integer.parseInt(jTID.getText()));
         
         jTNombre.setText(huesped.getNombre());
         jTApellido.setText(huesped.getApellido());
         jTDni.setText(String.valueOf(huesped.getDni()));
         jTDomicilio.setText(huesped.getDomicilio());
         jTCorreo.setText(huesped.getCorreo());
         jTelefono.setText(String.valueOf(huesped.getTelefono()));
         jRBActivo.setSelected(huesped.isActivo());
       }
       else
           if(!jTDni.getText().equals(""))
           {  huesped=hd.buscarHuespedPorDni(Integer.parseInt(jTDni.getText()));              
              
              jTID.setText(String.valueOf(huesped.getIdhuesped()));
              jTNombre.setText(huesped.getNombre());
              jTApellido.setText(huesped.getApellido());
              jTDomicilio.setText(huesped.getDomicilio());
              jTCorreo.setText(huesped.getCorreo());
              jTelefono.setText(String.valueOf(huesped.getTelefono()));
              jRBActivo.setSelected(huesped.isActivo());
           }
          else
               JOptionPane.showMessageDialog(null, "Los campos ID o DNI no pueden estar vacios");
    }//GEN-LAST:event_jBuscarActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
       Conexion con = new Conexion();
       HuespedData hd = new HuespedData(con);
             
         if (vacio())
       { JOptionPane.showMessageDialog(null, "Hay campos vacios, verifique antes de guardar");}
       else
       { int idHuesped=Integer.parseInt(jTID.getText());
         String nombre= jTNombre.getText();
         String apellido=jTApellido.getText();
         int dni=Integer.parseInt(jTDni.getText());
         String domicilio=jTDomicilio.getText();
         String correo=jTCorreo.getText();
         String telefono= jTelefono.getText();
         boolean activo=jRBActivo.isSelected();
       
         Huesped huesped= new Huesped(nombre, apellido, dni, domicilio, correo, telefono, activo);
       
         hd.modificarHuesped(idHuesped,huesped);
       }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
       Conexion con = new Conexion();
       HuespedData hd = new HuespedData(con);
       
       Integer id= Integer.parseInt(jTID.getText());
       
       if (jRBActivo.isSelected())
           hd.eliminarHuesped(id);
         else
           JOptionPane.showMessageDialog(null," Verifica la casilla que indica si esta activo o no el huseped");
    }//GEN-LAST:event_jBEliminarActionPerformed

private void limpiar()  
{ jTID.setText("");
  jTNombre.setText("");
  jTApellido.setText("");
  jTDni.setText("");
  jTDomicilio.setText("");
  jTCorreo.setText("");
  jTelefono.setText("");
  jRBActivo.setSelected(false);
  inicializar();
}

private void desactivarCText()
{       jTID.setEnabled(false);
        jTNombre.setEnabled(false);
        jTApellido.setEnabled(false);
        jTDni.setEnabled(false);
        jTDomicilio.setEnabled(false);
        jTCorreo.setEnabled(false);
        jTelefono.setEnabled(false);
        jRBActivo.setEnabled(false);
}

private void activarCText()
{       jTID.setEnabled(true);
        jTNombre.setEnabled(true);
        jTApellido.setEnabled(true);
        jTDni.setEnabled(true);
        jTDomicilio.setEnabled(true);
        jTCorreo.setEnabled(true);
        jTelefono.setEnabled(true);
        jRBActivo.setEnabled(true);
}

private void inicializar()
{       jBNuevo.setEnabled(true);
        jBNuevaBusqueda.setEnabled(true);
        jBuscar.setEnabled(false);
        jBGuardar.setEnabled(false);
        jBModificar.setEnabled(false);
        jBEliminar.setEnabled(false);
        jBLimpiar.setEnabled(true);
}
private boolean vacio()
{ boolean vacio=false;

    if (jTNombre.getText().equals("") || jTApellido.getText().equals("") || jTDni.getText(
       ).equals("")|| jTDomicilio.getText().equals("")|| jTCorreo.getText().equals("")||
       jTelefono.equals(""))
    {  vacio=true;
       
    }
  return(vacio);
}

public void noNumero(java.awt.event.KeyEvent evt)
{  if(!Character.isDigit(evt.getKeyChar()))
{  //getToolkit().beep();
  evt.consume();
}
}

public void noCaracter(java.awt.event.KeyEvent evt)
{  if(!(Character.isLetter(evt.getKeyChar())||evt.getKeyChar()== KeyEvent.VK_SPACE))
evt.consume();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBNuevaBusqueda;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRBActivo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JTextField jTCorreo;
    private javax.swing.JTextField jTDni;
    private javax.swing.JTextField jTDomicilio;
    private javax.swing.JTextField jTID;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTelefono;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel{
        private Image imagen;
        @Override
        public void paint (Graphics g){
            imagen = new ImageIcon(getClass().getResource("/imagen/huesped1.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
          
    }
}
