
package Vistas;

import com.jtattoo.plaf.mint.MintLookAndFeel;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author La Bestia
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(570, 520); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane(){
            String str="/imagen/hotel2.jpg";
            ImageIcon icon = new ImageIcon(getClass().getResource(str));
            Image image = icon.getImage();

            public void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(image, 0, 0,getWidth(),getHeight(), this);
            }};
            jMenuBar1 = new javax.swing.JMenuBar();
            menuHuesped = new javax.swing.JMenu();
            itemHuesped = new javax.swing.JMenuItem();
            MenuHabitacion = new javax.swing.JMenu();
            itemHabitacion = new javax.swing.JMenuItem();
            menuReserva = new javax.swing.JMenu();
            itemReserva = new javax.swing.JMenuItem();
            menuCategoria = new javax.swing.JMenu();
            itemCategoria = new javax.swing.JMenuItem();
            menuSalir = new javax.swing.JMenu();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setTitle("Gran Hotel Palace - Sistema de Reservas");
            setMinimumSize(new java.awt.Dimension(700, 600));

            escritorio.setPreferredSize(new java.awt.Dimension(800, 600));

            javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
            escritorio.setLayout(escritorioLayout);
            escritorioLayout.setHorizontalGroup(
                escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 778, Short.MAX_VALUE)
            );
            escritorioLayout.setVerticalGroup(
                escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 508, Short.MAX_VALUE)
            );

            menuHuesped.setText("Huesped");

            itemHuesped.setText("Agregar Huesped");
            itemHuesped.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    itemHuespedActionPerformed(evt);
                }
            });
            menuHuesped.add(itemHuesped);

            jMenuBar1.add(menuHuesped);

            MenuHabitacion.setText("Habitacion");

            itemHabitacion.setText("Formulario habitacion");
            itemHabitacion.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    itemHabitacionActionPerformed(evt);
                }
            });
            MenuHabitacion.add(itemHabitacion);

            jMenuBar1.add(MenuHabitacion);

            menuReserva.setText("Reserva");

            itemReserva.setText("Reservas");
            itemReserva.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    itemReservaActionPerformed(evt);
                }
            });
            menuReserva.add(itemReserva);

            jMenuBar1.add(menuReserva);

            menuCategoria.setText("Categoria");

            itemCategoria.setText("Categorias");
            itemCategoria.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    itemCategoriaActionPerformed(evt);
                }
            });
            menuCategoria.add(itemCategoria);

            jMenuBar1.add(menuCategoria);

            menuSalir.setText("Salir");
            menuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    menuSalirMouseClicked(evt);
                }
            });
            jMenuBar1.add(menuSalir);

            setJMenuBar(jMenuBar1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
                    .addGap(23, 23, 23))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void itemHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHabitacionActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        FormularioHabitacionView habitacion = new FormularioHabitacionView();
        habitacion.setVisible(true);
        habitacion.getContentPane().setBackground(new Color(68, 167, 132));
        escritorio.add(habitacion);
    }//GEN-LAST:event_itemHabitacionActionPerformed

    private void itemReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReservaActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        FormularioReservaView habitacion = new FormularioReservaView();
        habitacion.setVisible(true);
        habitacion.getContentPane().setBackground(new Color(68, 167, 132));
        escritorio.add(habitacion);
    }//GEN-LAST:event_itemReservaActionPerformed

    private void itemCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCategoriaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioCategoriaView categoria = new FormularioCategoriaView();
        categoria.setVisible(true);
        categoria.getContentPane().setBackground(new Color(68, 167, 132));
        escritorio.add(categoria);
    }//GEN-LAST:event_itemCategoriaActionPerformed

    private void itemHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHuespedActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioHuespedView huesped = new FormularioHuespedView();
        huesped.setVisible(true);
        huesped.getContentPane().setBackground(new Color(68, 167, 132));
        escritorio.add(huesped);
    }//GEN-LAST:event_itemHuespedActionPerformed

    private void menuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSalirMouseClicked
         dispose();
    }//GEN-LAST:event_menuSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new MintLookAndFeel());
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
                }
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuHabitacion;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem itemCategoria;
    private javax.swing.JMenuItem itemHabitacion;
    private javax.swing.JMenuItem itemHuesped;
    private javax.swing.JMenuItem itemReserva;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCategoria;
    private javax.swing.JMenu menuHuesped;
    private javax.swing.JMenu menuReserva;
    private javax.swing.JMenu menuSalir;
    // End of variables declaration//GEN-END:variables
}
