/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Color;

/**
 *
 * @author La Bestia
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(570, 520); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuHuesped = new javax.swing.JMenu();
        itemHuesped = new javax.swing.JMenuItem();
        menuCategoria = new javax.swing.JMenu();
        itemCategoria = new javax.swing.JMenuItem();
        MenuHabitacion = new javax.swing.JMenu();
        itemHabitacion = new javax.swing.JMenuItem();
        menuReserva = new javax.swing.JMenu();
        itemReserva = new javax.swing.JMenuItem();
        itemListado = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gran Hotel Palace ");
        setMinimumSize(new java.awt.Dimension(700, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/recepcionista.png"))); // NOI18N
        jLabel1.setLabelFor(escritorio);
        jLabel1.setName(""); // NOI18N

        escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menuHuesped.setText("Huesped");

        itemHuesped.setText("Agregar Huesped");
        itemHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemHuespedActionPerformed(evt);
            }
        });
        menuHuesped.add(itemHuesped);

        jMenuBar1.add(menuHuesped);

        menuCategoria.setText("Categoria");

        itemCategoria.setText("Categorias");
        itemCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCategoriaActionPerformed(evt);
            }
        });
        menuCategoria.add(itemCategoria);

        jMenuBar1.add(menuCategoria);

        MenuHabitacion.setText("Habitacion");

        itemHabitacion.setText("Formulario habitacion");
        itemHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemHabitacionActionPerformed(evt);
            }
        });
        MenuHabitacion.add(itemHabitacion);

        jMenuBar1.add(MenuHabitacion);

        menuReserva.setText("Reserva");

        itemReserva.setText("Reservas");
        itemReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReservaActionPerformed(evt);
            }
        });
        menuReserva.add(itemReserva);

        itemListado.setText("Precio");
        menuReserva.add(itemListado);

        jMenuBar1.add(menuReserva);

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHabitacionActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        FormularioHabitacionView habitacion = new FormularioHabitacionView();
        habitacion.setVisible(true);
        habitacion.getContentPane().setBackground(new Color(68, 167, 132));
        escritorio.add(habitacion);
    }//GEN-LAST:event_itemHabitacionActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void itemReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReservaActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        FormularioReservaView habitacion = new FormularioReservaView();
        habitacion.setVisible(true);
        habitacion.getContentPane().setBackground(new Color(68, 167, 132));
        escritorio.add(habitacion);
    }//GEN-LAST:event_itemReservaActionPerformed

    private void itemCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCategoriaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioCategoriaView categoria = new FormularioCategoriaView();
        categoria.setVisible(true);
        categoria.getContentPane().setBackground(new Color(68, 167, 132));
        escritorio.add(categoria);
    }//GEN-LAST:event_itemCategoriaActionPerformed

    private void itemHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHuespedActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioHuespedView huesped = new FormularioHuespedView();
        huesped.setVisible(true);
        huesped.getContentPane().setBackground(new Color(68, 167, 132));
        escritorio.add(huesped);
    }//GEN-LAST:event_itemHuespedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuHabitacion;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem itemCategoria;
    private javax.swing.JMenuItem itemHabitacion;
    private javax.swing.JMenuItem itemHuesped;
    private javax.swing.JMenuItem itemListado;
    private javax.swing.JMenuItem itemReserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCategoria;
    private javax.swing.JMenu menuHuesped;
    private javax.swing.JMenu menuReserva;
    private javax.swing.JMenu menuSalir;
    // End of variables declaration//GEN-END:variables
}
